# Generated by Django 5.2.3 on 2026-02-16 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        ('raffles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(help_text='Payload completo del webhook')),
                ('status', models.CharField(choices=[('received', 'Recibido'), ('valid', 'Válido'), ('invalid_signature', 'Firma inválida'), ('invalid_json', 'JSON inválido'), ('missing_reference', 'Reference faltante'), ('purchase_not_found', 'Purchase no encontrada'), ('processed', 'Procesado'), ('error', 'Error')], default='received', max_length=30)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('resultado_transaccion', models.CharField(blank=True, max_length=50, null=True)),
                ('signature_valid', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raffles.raffle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
