"""
Django settings for tixiProject project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import re
import dj_database_url
from decouple import Csv, config
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    'SECRET_KEY',
    default='django-insecure-mh-f8x)k&crdlmb%cfg_w--8$3-lb&%&^^((0wg9lf0y%wzqex'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

APPEND_SLASH = True
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'accounts',

    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    
    'rest_framework',

    'raffles',
    'payments',
    'draws',
    'dashboard',
    'channels',

    'django_unicorn',
]

SITE_ID = 1
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'


ACCOUNT_EMAIL_VERIFICATION = config('ACCOUNT_EMAIL_VERIFICATION', default='none')
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_DEFAULT_HTTP_PROTOCOL = config('ACCOUNT_DEFAULT_HTTP_PROTOCOL', default='https')
LOGIN_REDIRECT_URL = '/'
SOCIALACCOUNT_ONLY = config('SOCIALACCOUNT_ONLY', default=False, cast=bool)
if SOCIALACCOUNT_ONLY:
    ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_LOGIN_BY_CODE_ENABLED = config('ACCOUNT_LOGIN_BY_CODE_ENABLED', default=False, cast=bool)
ACCOUNT_LOGIN_BY_CODE_REQUIRED = config('ACCOUNT_LOGIN_BY_CODE_REQUIRED', default=False, cast=bool)
ACCOUNT_LOGIN_BY_CODE_TIMEOUT = config('ACCOUNT_LOGIN_BY_CODE_TIMEOUT', default=180, cast=int)
ACCOUNT_LOGIN_BY_CODE_MAX_ATTEMPTS = config('ACCOUNT_LOGIN_BY_CODE_MAX_ATTEMPTS', default=3, cast=int)

EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend'
)
EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=False, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='no-reply@tixipwa.local')
SERVER_EMAIL = config('SERVER_EMAIL', default=DEFAULT_FROM_EMAIL)

ASGI_APPLICATION = "tixiProject.asgi.application"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tixiProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tixiProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = config('DATABASE_URL', default='').strip()

if DATABASE_URL.upper().startswith('DATABASE_URL='):
    DATABASE_URL = DATABASE_URL.split('=', 1)[1].strip()

DATABASE_URL = DATABASE_URL.strip('"').strip("'")

if DATABASE_URL:
    if '://' not in DATABASE_URL:
        raise ValueError(
            "DATABASE_URL inválida. Usa formato completo, por ejemplo: "
            "postgresql://USER:PASSWORD@HOST:PORT/DBNAME?sslmode=require"
        )

    db_scheme = DATABASE_URL.split('://', 1)[0].lower()
    ssl_supported_schemes = {'postgres', 'postgresql', 'mysql', 'mysql2'}
    ssl_require = (
        config('DATABASE_SSL_REQUIRE', default=True, cast=bool)
        if db_scheme in ssl_supported_schemes
        else False
    )

    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=ssl_require,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

if not DEBUG:
    if not SECRET_KEY or SECRET_KEY.startswith('django-insecure-'):
        raise ImproperlyConfigured('SECRET_KEY segura es requerida en producción')
    if not DATABASE_URL:
        raise ImproperlyConfigured('DATABASE_URL es requerida cuando DEBUG=False')


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (User uploads)
USE_DO_SPACES = config('USE_DO_SPACES', default=False, cast=bool)


def _is_valid_bucket_name(bucket_name):
    if not bucket_name:
        return False
    bucket_name = bucket_name.strip()
    pattern = r'^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$'
    return bool(re.match(pattern, bucket_name))


DO_SPACES_BUCKET = config('DO_SPACES_BUCKET', default='').strip()
DO_SPACES_KEY = config('DO_SPACES_KEY', default='').strip()
DO_SPACES_SECRET = config('DO_SPACES_SECRET', default='').strip()

USE_DO_SPACES = USE_DO_SPACES and _is_valid_bucket_name(DO_SPACES_BUCKET) and bool(DO_SPACES_KEY) and bool(DO_SPACES_SECRET)

if USE_DO_SPACES:
    AWS_ACCESS_KEY_ID = DO_SPACES_KEY
    AWS_SECRET_ACCESS_KEY = DO_SPACES_SECRET
    AWS_STORAGE_BUCKET_NAME = DO_SPACES_BUCKET
    AWS_S3_REGION_NAME = config('DO_SPACES_REGION', default='nyc3')
    AWS_S3_ENDPOINT_URL = config(
        'DO_SPACES_ENDPOINT_URL',
        default=f'https://{AWS_S3_REGION_NAME}.digitaloceanspaces.com'
    )
    AWS_S3_CUSTOM_DOMAIN = config(
        'DO_SPACES_CDN_DOMAIN',
        default=f'{AWS_STORAGE_BUCKET_NAME}.{AWS_S3_REGION_NAME}.digitaloceanspaces.com'
    )
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_FILE_OVERWRITE = False
    AWS_LOCATION = config('DO_SPACES_LOCATION', default='media')

    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3.S3Storage',
            'OPTIONS': {
                'location': AWS_LOCATION,
            },
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }

    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}/'
    MEDIA_ROOT = BASE_DIR / 'media'
    SERVE_MEDIA = False
else:
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'
    SERVE_MEDIA = config('SERVE_MEDIA', default=DEBUG, cast=bool)

# 🔐 Configuración de Wompi para webhooks
# ========================================
# Descomenta y configura con tus valores reales
WOMPI_API_SECRET = config('WOMPI_API_SECRET', default='')
WOMPI_INTEGRITY_KEY = config('WOMPI_INTEGRITY_KEY', default='')
WOMPI_PUBLIC_KEY = config('WOMPI_PUBLIC_KEY', default='')
WOMPI_PRIVATE_KEY = config('WOMPI_PRIVATE_KEY', default='')

# URL para tunneling en desarrollo (ej: ngrok)
NGROK_URL = config('NGROK_URL', default='')

# 📝 Logging para webhooks
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} - {name} - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'payments.webhooks': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'allauth': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'ERROR',
    },
}

CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='https://tixxi.io,https://www.tixxi.io',
    cast=Csv()
)


ALLOWED_HOSTS = [
    host.strip() for host in config(
        'ALLOWED_HOSTS',
        default='tixxi.io, www.tixxi.io',
        cast=Csv()
    ) if host.strip()
]

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

if not DEBUG:
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=31536000, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=True, cast=bool)
    SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=True, cast=bool)
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = config('SECURE_REFERRER_POLICY', default='same-origin')
    X_FRAME_OPTIONS = config('X_FRAME_OPTIONS', default='DENY')

REDIS_URL = config('REDIS_URL', default='')

if REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [REDIS_URL],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }

def _clean_env(value):
    return (value or '').strip().strip('"').strip("'")


GOOGLE_CLIENT_ID = _clean_env(config('GOOGLE_CLIENT_ID', default=''))
GOOGLE_CLIENT_SECRET = _clean_env(config('GOOGLE_CLIENT_SECRET', default=''))

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'APP': {
            'client_id': GOOGLE_CLIENT_ID,
            'secret': GOOGLE_CLIENT_SECRET,
            'key': ''
        }
    }
}

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

APP_BASE_URL = config('APP_BASE_URL', default='').strip().rstrip('/')