# Generated by Django 5.2.3 on 2026-03-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draws', '0002_draw_winner_comment_and_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draw',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
