# Generated by Django 5.2.3 on 2026-02-17 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0002_rafflelistmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaffleMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='raffles/%Y/%m/%d/')),
                ('media_type', models.CharField(choices=[('image', 'Imagen'), ('video', 'Video')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='raffles.raffle')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.DeleteModel(
            name='RaffleListMedia',
        ),
    ]
