# Generated by Django 5.2.3 on 2026-02-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0004_homecarouselslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecarouselslide',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
